sudo: required
dist: trusty

language: c

matrix:
  include:
    - go: 1.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu libvirt-bin -qq
  - cd `mktemp -d`
  - wget https://git.fedorahosted.org/cgit/lvm2.git/snapshot/lvm2-2_02_131.tar.xz
  - tar xf lvm2-2_02_131.tar.xz
  - cd lvm2-2_02_131
  - ./configure && make device-mapper && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./autogen.sh
  - ./configure
  - make
  - hack/test-cmd.sh
