sudo: required
dist: trusty

language: go

go:
  - 1.8

env:
  - HYPER_EXEC_DRIVER=qemu    HYPER_STORAGE_DRIVER=rawblock
  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=overlay

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu libvirt-bin linux-headers-$(uname -r)
  - sudo mkdir -p /usr/include/linux
  - sudo cp /usr/src/linux-headers-$(uname -r)/include/uapi/linux/vm_sockets.h /usr/include/linux
  - cd `mktemp -d`
  - wget ftp://sources.redhat.com/pub/lvm2/LVM2.2.02.131.tgz
  - tar xf LVM2.2.02.131.tgz
  - cd LVM2.2.02.131
  - ./configure && make device-mapper && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./autogen.sh
  - ./configure
  - make
  - hack/test-cmd.sh
